/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/25/23, 5:15 PM' 
 * Generated by 'surya' 
 * Generated on server 'LAPTOP-L5PCGM70.HSD1.CT.COMCAST.NET' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:53930/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257B7ABF8D65-694D-41E0-B4A0-CEBA100365A1%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.AIRPORT_FIVE out=Work.preProcessedData1;
	by Date;
run;

TITLE 'Analysis for LAX'
proc timeseries data=Work.preProcessedData1 seasonality=12 plots=(series cycles 
		corr decomp tc sc);
	id Date interval=month;
	var Passengers_LAX / accumulate=none transform=none dif=0 sdif=0;
	decomp tc seasonal / mode=multoradd;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData1 plots=none;
	ods select StationarityTests;
	identify var=Passengers_LAX stationarity=(adf=2);
	run;
quit;

TITLE 'Analysis for JFK'

proc timeseries data=Work.preProcessedData1 seasonality=12 plots=(series cycles 
		corr decomp tc sc);
	id Date interval=month;
	var Passengers_JFK / accumulate=none transform=none dif=0 sdif=0;
	decomp tc seasonal / mode=multoradd;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData1 plots=none;
	ods select StationarityTests;
	identify var=Passengers_JFK stationarity=(adf=2);
	run;
quit;


TITLE 'Analysis for ATL'
proc timeseries data=Work.preProcessedData1 seasonality=12 plots=(series cycles 
		corr decomp tc sc);
	id Date interval=month;
	var Passengers_ATL / accumulate=none transform=none dif=0 sdif=0;
	decomp tc seasonal / mode=multoradd;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData1 plots=none;
	ods select StationarityTests;
	identify var=Passengers_ATL stationarity=(adf=2);
	run;
quit;

TITLE 'Analysis for ORD'
proc timeseries data=Work.preProcessedData1 seasonality=12 plots=(series cycles 
		corr decomp tc sc);
	id Date interval=month;
	var Passengers_ORD / accumulate=none transform=none dif=0 sdif=0;
	decomp tc seasonal / mode=multoradd;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData1 plots=none;
	ods select StationarityTests;
	identify var=Passengers_ORD stationarity=(adf=2);
	run;
quit;

TITLE 'Analysis for DFW'
proc timeseries data=Work.preProcessedData1 seasonality=12 plots=(series cycles 
		corr decomp tc sc);
	id Date interval=month;
	var Passengers_DFW / accumulate=none transform=none dif=0 sdif=0;
	decomp tc seasonal / mode=multoradd;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData1 plots=none;
	ods select StationarityTests;
	identify var=Passengers_DFW stationarity=(adf=2);
	run;
quit;


proc delete data=Work.preProcessedData1;
run;